---
- name: Install Brave repo
  shell: sudo dnf-3 config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
  args:
    creates: /etc/yum.repos.d/brave-browser.repo

- name: Install Brave key
  rpm_key:
    key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    state: present

- name: Install Brave packages
  dnf:
    name:
      - brave-browser
    state: present
