---
- name: Uninstall Docker CE packages
  dnf:
    name:
      - docker-ce
      - docker-ce-rootless-extras
    state: absent

- name: Install Docker packages
  dnf:
    name:
      - docker-cli
      - docker-compose
      # - golang-github-rootless-containers-rootlesskit
      # - moby-engine-rootless-extras
    state: present

- name: Modify /etc/default/grub
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX="[\w](?!.*\b{{ item }}\b).*)"$'
    replace: '\1 {{ item }}"'
  with_items:
    - "cgroup_enable=memory"
    - "intel_iommu=on"
    - "iommu=pt"

- name: Copy daemon.json
  copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'

- name: Enable Docker service
  systemd_service:
    name: docker
    enabled: true
    masked: no
    state: started

- name: Install dockerd-rootless scripts
  get_url:
    url: "https://raw.githubusercontent.com/moby/moby/refs/heads/master/contrib/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0555'
  loop:
    - dockerd-rootless.sh
    - dockerd-rootless-setuptool.sh
