---
- name: Install Docker repo
  shell: sudo dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker packages
  dnf:
    name:
      - docker-ce
    state: present

- name: Modify /etc/default/grub
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX="[\w](?!.*\b{{ item }}\b).*)"$'
    replace: '\1 {{ item }}"'
  with_items:
    - "cgroup_enable=memory"
    - "intel_iommu=on"
    - "iommu=pt"

- name: Enable Docker service
  systemd_service:
    name: docker
    enabled: true
    masked: no
    state: started
