---
- name: Install GH cli repo
  shell: sudo dnf config-manager addrepo --from-repofile=https://cli.github.com/packages/rpm/gh-cli.repo
  args:
    creates: /etc/yum.repos.d/gh-cli.repo

- name: Install GH cli packages
  dnf:
    name:
      - gh
    state: present
