---
- name: Install Opera key
  rpm_key:
    key: https://rpm.opera.com/rpmrepo.key
    state: present
  tags: ['dnf', 'opera']

- name: Install Opera repo
  yum_repository:
    name: opera
    description: Opera packages
    baseurl: 'https://rpm.opera.com/rpm'
    gpgcheck: true
    gpgkey: 'https://rpm.opera.com/rpmrepo.key'
  tags: ['dnf', 'opera']

- name: Install Opera packages
  dnf:
    name:
      - opera-stable
    state: present
    update_cache: true
  tags: ['dnf', 'opera']
