---
- name: Install packages
  dnf:
    name:
      - avahi-tools
      - bats
      - bind-utils
      - blueman-nautilus
      - bsdtar
      - btrfs-progs
      - buildah
      - chromium
      - cifs-utils
      - curl
      - dejavu-fonts-all
      - distribution-gpg-keys
      - exfatprogs
      - e2fsprogs
      - fakeroot
      - firefox
      - firefox-wayland
      - gcc
      - git
      - gnome-extensions-app
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-tweaks
      - gnutls-utils
      - golang-bin
      - golang-honnef-tools
      - jetbrains-mono-fonts-all
      - jq
      - ImageMagick
      - keepassxc
      - libva-utils
      - libvirt-client
      - lsscsi
      - lshw
      - lsof
      - ltrace
      - lynx
      - make
      - man-pages-posix
      - mc
      - mtr
      - nautilus-gsconnect
      - netcat
      - net-tools
      - nextcloud-client
      - nmap
      - nmap-ncat
      - nss-tools
      - patch
      - perltidy
      - pigz
      - podman
      - podman-remote
      - podmansh
      - openssl
      - procinfo
      - python3-devel
      - python3-virtualenv
      - qemu-tools
      - rclone
      - rpcbind
      - rpmconf
      - rsync
      - screen
      - sg3_utils
      - ShellCheck
      - skopeo
      - smartmontools
      - snapd
      - socat
      - strace
      - subversion
      - tcpdump
      - thunderbird
      - thunderbird-wayland
      - tilix
      - traceroute
      - transmission
      - unzip
      - vim
      - virt-manager
      - virt-viewer
      - xfsprogs
      - xsel
      - wget
      - zip
      - zstd
    state: present
  tags: ['dnf']

- name: Install package groups
  dnf:
    name:
      - '@c-development'
      - '@container-management'
      - '@development-tools'
      - '@virtualization'
    state: present
  tags: ['dnf']

- name: Uninstall packages
  dnf:
    name:
      - bash-color-prompt
      - cups
      - rhythmbox
      - virtualbox-guest-additions
    state: absent
  tags: ['dnf']

- name: Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes
  tags: ['dnf']
