---
- name: Install packages
  dnf:
    name:
      - avahi-tools
      - bats
      - bcc
      - bcc-doc
      - bind-utils
      - blueman-nautilus
      - bsdtar
      - btrfs-progs
      - buildah
      - captree
      - chromium
      - cifs-utils
      - clang
      - cmake
      - curl
      - dejavu-fonts-all
      - distribution-gpg-keys
      - e2fsprogs
      - efitools
      - exfatprogs
      - fakeroot
      - firefox
      - ftp
      - gcc
      - gh
      - git
      - glab
      - glibc-devel
      - glibc-devel.i686
      - glibc-static
      - glibc-static.i686
      - gnome-extensions-app
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-themes-extra
      - gnome-tweaks
      - gnutls-utils
      - hexchat
      - httpd-tools
      - ImageMagick
      - jetbrains-mono-fonts-all
      - jq
      - kata-containers
      - keepassxc
      - kernel-modules-extra
      - lbzip2
      - libbsd-devel
      - libcap-ng-utils
      - libva-utils
      - libvirt-client
      - lldb
      - llvm
      - lsscsi
      - lshw
      - lsof
      - ltrace
      - lynx
      - make
      - mc
      - mtr
      - moreutils
      - nautilus-gsconnect
      - netcat
      - net-tools
      - nextcloud-client
      - nmap
      - nmap-ncat
      - nss-tools
      - oci-seccomp-bpf-hook
      - patch
      - pbzip2
      - perltidy
      - pigz
      - pipewire-codec-aptx
      - podman
      - podman-remote
      - podmansh
      - openssl
      - procinfo
      - python3-devel
      - python3-dnf-plugin-versionlock
      - python3-virtualenv
      - qemu-tools
      - rclone
      - rpcbind
      - rpmconf
      - rsync
      - screen
      - setools-console
      - sg3_utils
      - sharutils
      - ShellCheck
      - skopeo
      - smartmontools
      - socat
      - strace
      - subversion
      - sysfsutils
      - tcpdump
      - terminator
      - thunderbird
      - tilix
      - tmux
      - traceroute
      - transmission
      - unzip
      - vim
      - virt-manager
      - virt-viewer
      - xfsprogs
      - xsel
      - wget
      - wodim
      - xorg-x11-server-Xvfb
      - xrandr
      - zip
      - zstd
    state: present

- name: Install package groups
  dnf:
    name:
      - '@c-development'
      - '@container-management'
      - '@development-tools'
      - '@virtualization'
    state: present

- name: Uninstall packages
  dnf:
    name:
      - bash-color-prompt
      - cups
      - fprintd
      - gnome-user-share
      - mediawriter
      - open-vm-tools
      - rhythmbox
      - snapd
      - virtualbox-guest-additions
    state: absent

- name: Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes
