---
- name: Install packages
  dnf:
    name:
      - aria2
      - avahi-tools
      - bcc
      - bcc-doc
      - bind-utils
      - blueman-nautilus
      - bmake
      - bsdcat
      - bsdtar
      - btrfs-progs
      - buildah
      - captree
      - chromium
      - cifs-utils
      - clang
      - cmake
      - curl
      - dejavu-fonts-all
      - distribution-gpg-keys
      - e2fsprogs
      - exfatprogs
      - fakeroot
      - firefox
      - gcc
      - gdisk
      - gh
      - git
      - glab
      - glibc-devel
      - glibc-static
      - gnome-extensions-app
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-themes-extra
      - gnome-tweaks
      - gnutls-utils
      - gperf
      - httpd-tools
      - ImageMagick
      - jetbrains-mono-fonts-all
      - jq
      - kata-containers
      - keepassxc
      - kernel-modules-extra
      - lbzip2
      - libbsd-devel
      - libcap-ng-utils
      - libcgroup-tools
      - libva-utils
      - libvirt-client
      - lldb
      - llvm
      - lsscsi
      - lshw
      - lsof
      - ltrace
      - lynx
      - make
      - mawk
      - mandoc
      - mc
      - mtr
      - moreutils
      - nautilus-gsconnect
      - nawk
      - netcat
      - net-tools
      - nextcloud-client
      - nss-tools
      - oci-seccomp-bpf-hook
      - patch
      - pbzip2
      - perltidy
      - pigz
      - podman
      - podman-remote
      - openssl
      - procinfo
      - python3-devel
      - python3-dnf-plugin-versionlock
      - python3-virtualenv
      - qemu-tools
      - rclone
      - rpcbind
      - rpmconf
      - rsync
      - setools-console
      - sg3_utils
      - sharutils
      - ShellCheck
      - skopeo
      - smartmontools
      - socat
      - strace
      - subversion
      - sysfsutils
      - tcpdump
      - terminator
      - thunderbird
      - tilix
      - tmux
      - tnftp
      - traceroute
      - transmission
      - unzip
      - vim
      - virt-manager
      - virt-viewer
      - xfsprogs
      - xsel
      - wget
      - wodim
      - xorg-x11-server-Xvfb
      - xrandr
      - yq
      - zip
      - zstd
    state: present

- name: Install package groups
  dnf:
    name:
      - '@c-development'
      - '@container-management'
      - '@development-tools'
      - '@virtualization'
    state: present

- name: Uninstall packages
  dnf:
    name:
      - bash-color-prompt
      - bluez-cups
      - braille-printer-app
      - cups
      - cups-browsed
      - cups-filters*
      - fprintd
      - fprintd-pam
      - gnome-user-share
      - gutenprint
      - gutenprint-cups
      - hplip
      - libppd
      - mediawriter
      - open-vm-tools*
      - rhythmbox
      - virtualbox-guest-additions
    state: absent

- name: Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes
