---
- name: Install security packages
  dnf:
    name:
      - opendoas
    state: present

- name: Configure doas
  copy:
    src: doas.conf
    dest: /etc/doas.conf
    owner: root
    group: wheel
    mode: 0600

- name: Enable sudo insults
  copy:
    src: sudoers.d/insults
    dest: /etc/sudoers.d/insults
    owner: root
    group: root
    mode: 0600
