---
- name: Install security packages
  dnf:
    name:
      - opendoas
    state: present

- name: Configure doas
  copy:
    src: doas.conf
    dest: /etc/doas.conf
    owner: root
    group: wheel
    mode: 0600
