---
- name: Install Slack key
  rpm_key:
    key: https://packagecloud.io/gpg.key
    state: present
  tags: ['dnf', 'slack']

- name: Install Slack repo
  yum_repository:
    name: slack
    description: slack
    baseurl: 'https://packagecloud.io/slacktechnologies/slack/fedora/21/$basearch'
    gpgcheck: false
  tags: ['dnf', 'slack']

- name: Install Slack packages
  dnf:
    name:
      - slack
    state: present
    update_cache: true
  tags: ['dnf', 'slack']

- name: Turn off noisy logging by crappy Slack app
  lineinfile:
    path: /usr/share/applications/slack.desktop
    regexp: '^Exec='
    line: 'Exec=/usr/bin/slack -g warn %U'
  tags: ['slack']
