---
- name: Install Tuxedo key
  rpm_key:
    key: https://rpm.tuxedocomputers.com/fedora/$releasever/0x54840598.pub.asc
    state: present
  tags: ['dnf', 'tuxedo']

- name: Install Tuxedo repo
  yum_repository:
    name: tuxedo
    description: tuxedo
    baseurl: 'https://rpm.tuxedocomputers.com/fedora/$releasever/$basearch/base'
    enabled: true
    gpgcheck: true
    gpgkey: 'https://rpm.tuxedocomputers.com/fedora/$releasever/0x54840598.pub.asc'
  tags: ['dnf', 'tuxedo']

- name: Install Tuxedo packages
  dnf:
    name:
      - tuxedo-control-center
  tags: ['dnf', 'tuxedo']

# Workaround for https://github.com/tuxedocomputers/tuxedo-control-center/issues/354
- name: Create tuxedo-control-center symlink
  shell: ln -s /opt/tuxedo-control-center/tuxedo-control-center /usr/bin/
  args:
    creates: /usr/bin/tuxedo-control-center
