---
- name: Install VSCode repo
  shell: sudo dnf config-manager --add-repo https://packages.microsoft.com/yumrepos/vscode/config.repo
  args:
    creates: /etc/yum.repos.d/config.repo

- name: Install VSCode packages
  dnf:
    name:
      - code
    state: present
