---
- name: Install Yubikey packages
  dnf:
    name:
      - pam-u2f 
      - pamu2fcfg
      - pam_yubico
      - pcsc-tools
      - ykpers
      - yubico-piv-tool
      - yubikey-manager
      - yubikey-manager-qt
      - yubikey-personalization-gui
    state: present

- name: Add custom udev rules for Yubikey
  copy:
    src: 70-u2f.rules
    dest: /etc/udev/rules.d/70-u2f.rules
    owner: root
    group: root
    mode: 0644
