---
- name: Install ZFS repo package
  shell: 'dnf install -y https://zfsonlinux.org/fedora/zfs-release-3-1$(rpm --eval "%{dist}").noarch.rpm'
  args:
    creates: /etc/yum.repos.d/zfs.repo

- name: Uninstall zfs-fuse
  dnf:
    name:
      - zfs-fuse
    state: absent

- name: Install ZFS packages & dependencies
  dnf:
    name:
      - kernel-devel-matched
      - zfs
    state: present

- name: Load ZFS module at boot
  shell: 'echo zfs > /etc/modules-load.d/zfs.conf'
  args:
    creates: /etc/modules-load.d/zfs.conf


